"""Migración inicial de modelos de API

Revision ID: cd2cc79e9ada
Revises: 
Create Date: 2025-11-12 16:58:54.918350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd2cc79e9ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('post_categoria', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_username'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    with op.batch_alter_table('post_categoria', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_column('is_visible')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
